# 🌐 OPTIMERAD REST Sensor för Vättern Badtemperatur
# Uppdaterad för Home Assistant 2024.x med moderna förbättringar

rest:
  - resource: "https://portal.loggamera.se/PublicViews/OverviewInside"
    method: POST
    payload: "id=22"
    headers:
      Content-Type: "application/x-www-form-urlencoded"
      User-Agent: "HomeAssistant/2024.1"
      Accept: "text/html,application/xhtml+xml"
    scan_interval: 300  # 5 minuter
    timeout: 30
    verify_ssl: true
    # Automatisk retry vid fel (ny feature)
    retry_on_failure: true
    retry_count: 3
    retry_delay: 10
    
    sensor:
      - name: "Vättern Badtemperatur"
        unique_id: "vattern_badtemperatur_rest_optimized"
        unit_of_measurement: "°C"
        device_class: "temperature"
        state_class: "measurement"
        icon: "mdi:waves"
        
        # Förbättrad parsing med bättre error handling
        value_template: >-
          {%- set temp_pattern = 'data-value="(-?\d+\.?\d*)"' -%}
          {%- set matches = value | regex_findall(temp_pattern) if value else [] -%}
          {%- if matches | length > 0 -%}
            {%- set valid_temps = [] -%}
            {%- for match in matches -%}
              {%- set temp = match | float(0) -%}
              {%- if temp >= -5 and temp <= 40 -%}
                {%- set valid_temps = valid_temps + [temp] -%}
              {%- endif -%}
            {%- endfor -%}
            {%- if valid_temps | length > 0 -%}
              {{ valid_temps[0] | round(1) }}
            {%- else -%}
              unavailable
            {%- endif -%}
          {%- else -%}
            unavailable
          {%- endif -%}
        
        # Förbättrad availability check
        availability: >-
          {% if value is defined and value %}
            {% set has_data = value | regex_search('data-value="(-?\d+\.?\d*)"') %}
            {% set not_error = not (value | lower).contains('error') %}
            {% set not_timeout = not (value | lower).contains('timeout') %}
            {% set min_length = value | length > 50 %}
            {{ has_data and not_error and not_timeout and min_length }}
          {% else %}
            false
          {% endif %}
        
        # Utökade attribut för debugging och monitoring
        attributes:
          last_updated: "{{ now().isoformat() }}"
          source: "Loggamera Portal"
          location_id: 22
          location_name: "Vättern, Hjo"
          data_source: "REST Sensor"
          scan_interval_minutes: 5
          # Debug info (kan tas bort i produktion)
          response_length: "{{ value | length if value else 0 }}"
          has_temperature_data: >-
            {{ value | regex_search('data-value="(-?\d+\.?\d*)"') is not none if value else false }}

# Valfri: Binary sensor för att övervaka om datasource är online
binary_sensor:
  - platform: template
    sensors:
      vattern_data_online:
        friendly_name: "Vättern Data Online"
        device_class: "connectivity"
        icon_template: >-
          {% if is_state('sensor.vattern_badtemperatur', 'unavailable') %}
            mdi:wifi-off
          {% else %}
            mdi:wifi
          {% endif %}
        value_template: >-
          {{ not is_state('sensor.vattern_badtemperatur', 'unavailable') }}
        attribute_templates:
          last_seen: >-
            {% if not is_state('sensor.vattern_badtemperatur', 'unavailable') %}
              {{ now().isoformat() }}
            {% else %}
              {{ state_attr('binary_sensor.vattern_data_online', 'last_seen') }}
            {% endif %}

# Automatisering för att logga när sensorn går offline
automation:
  - alias: "Vättern Sensor Offline Notification"
    description: "Notifierar när Vättern-sensorn är offline i mer än 15 minuter"
    trigger:
      - platform: state
        entity_id: sensor.vattern_badtemperatur
        to: "unavailable"
        for: "00:15:00"
    action:
      - service: persistent_notification.create
        data:
          title: "🌊 Vattentemperatur Sensor Offline"
          message: >
            Vättern badtemperatur-sensorn har varit offline sedan {{ trigger.from_state.last_changed | as_timestamp | timestamp_custom('%H:%M') }}.
            Kontrollera internetanslutning och Loggamera-tjänsten.
          notification_id: "vattern_sensor_offline"
      - service: system_log.write
        data:
          level: warning
          message: "Vättern temperature sensor offline for 15+ minutes"

  - alias: "Vättern Sensor Online Notification"
    description: "Rensar notifiering när sensorn kommer online igen"
    trigger:
      - platform: state
        entity_id: sensor.vattern_badtemperatur
        from: "unavailable"
    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state != 'unavailable' }}"
    action:
      - service: persistent_notification.dismiss
        data:
          notification_id: "vattern_sensor_offline"
      - service: system_log.write
        data:
          level: info
          message: "Vättern temperature sensor back online: {{ trigger.to_state.state }}°C" 